name: Flutter Shorebird CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.9"

      - name: Install Shorebird
        run: |
          curl -sSf https://raw.githubusercontent.com/shorebirdtech/install/main/install.sh | bash
          echo "$HOME/.shorebird/bin" >> $GITHUB_PATH

      - name: Verify Shorebird
        run: |
          ls -la $HOME/.shorebird/bin
          $HOME/.shorebird/bin/shorebird --version

      - name: Authenticate Shorebird
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
        run: $HOME/.shorebird/bin/shorebird login:ci --token "$SHOREBIRD_TOKEN"

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Build Android (Release)
        run: $HOME/.shorebird/bin/shorebird release android --artifact=apk

      - name: Create Patch (OTA)
        run: $HOME/.shorebird/bin/shorebird patch android
